# Generated by Django 2.2.5 on 2021-01-26 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreM', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreP', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMedico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.medico')),
                ('idPaciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.paciente')),
            ],
        ),
    ]
